#ifndef LIBRESOURCE_GLOBAL_H
#define LIBRESOURCE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBRESOURCE_LIBRARY)
#  define LIBRESOURCESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBRESOURCESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBRESOURCE_GLOBAL_H
